//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CSKeywords&gt;
        ///&lt;Keyword&gt;abstract&lt;/Keyword&gt;
        ///&lt;Keyword&gt;as&lt;/Keyword&gt;
        ///&lt;Keyword&gt;base&lt;/Keyword&gt;
        ///&lt;Keyword&gt;bool&lt;/Keyword&gt;
        ///&lt;Keyword&gt;break&lt;/Keyword&gt;
        ///&lt;Keyword&gt;byte&lt;/Keyword&gt;
        ///&lt;Keyword&gt;case&lt;/Keyword&gt;
        ///&lt;Keyword&gt;catch&lt;/Keyword&gt;
        ///&lt;Keyword&gt;char&lt;/Keyword&gt;
        ///&lt;Keyword&gt;checked&lt;/Keyword&gt;
        ///&lt;Keyword&gt;class&lt;/Keyword&gt;
        ///&lt;Keyword&gt;const&lt;/Keyword&gt;
        ///&lt;Keyword&gt;continue&lt;/Keyword&gt;
        ///&lt;Keyword&gt;decimal&lt;/Keyword&gt;
        ///&lt;Keyword&gt;default&lt;/Keyword&gt;
        ///&lt;Keyword&gt;delegate&lt;/Keyword&gt;
        ///&lt;Keyword&gt;do&lt;/Keyword&gt;
        ///&lt;Keyword&gt;do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpKeywords {
            get {
                return ResourceManager.GetString("CSharpKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Mappings&gt;
        ///	&lt;Mapping&gt;
        ///		&lt;SqlType&gt;char&lt;/SqlType&gt;
        ///		&lt;CsType&gt;string&lt;/CsType&gt;
        ///		&lt;Cs20NullableType&gt;string&lt;/Cs20NullableType&gt;
        ///		&lt;Cs11NullableType&gt;string&lt;/Cs11NullableType&gt;
        ///		&lt;CsConverter&gt;Convert.ToString&lt;/CsConverter&gt;
        ///	&lt;/Mapping&gt;
        ///	&lt;Mapping&gt;
        ///		&lt;SqlType&gt;varchar&lt;/SqlType&gt;
        ///		&lt;CsType&gt;string&lt;/CsType&gt;
        ///		&lt;Cs20NullableType&gt;string&lt;/Cs20NullableType&gt;
        ///		&lt;Cs11NullableType&gt;string&lt;/Cs11NullableType&gt;
        ///		&lt;CsConverter&gt;Convert.ToString&lt;/CsConverter&gt;
        ///	&lt;/Mapping&gt;
        ///	&lt;Mapping&gt;
        ///		&lt;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mappings {
            get {
                return ResourceManager.GetString("Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SQLKeywords&gt;
        ///&lt;Keyword&gt;ADD&lt;/Keyword&gt;
        ///&lt;Keyword&gt;EXISTS&lt;/Keyword&gt;
        ///&lt;Keyword&gt;PRIMARY&lt;/Keyword&gt;
        ///&lt;Keyword&gt;ALL&lt;/Keyword&gt;
        ///&lt;Keyword&gt;EXIT&lt;/Keyword&gt;
        ///&lt;Keyword&gt;PRINT&lt;/Keyword&gt;
        ///&lt;Keyword&gt;ALTER&lt;/Keyword&gt;
        ///&lt;Keyword&gt;EXTERNAL&lt;/Keyword&gt;
        ///&lt;Keyword&gt;PROC&lt;/Keyword&gt;
        ///&lt;Keyword&gt;AND&lt;/Keyword&gt;
        ///&lt;Keyword&gt;FETCH&lt;/Keyword&gt;
        ///&lt;Keyword&gt;PROCEDURE&lt;/Keyword&gt;
        ///&lt;Keyword&gt;ANY&lt;/Keyword&gt;
        ///&lt;Keyword&gt;FILE&lt;/Keyword&gt;
        ///&lt;Keyword&gt;PUBLIC&lt;/Keyword&gt;
        ///&lt;Keyword&gt;AS&lt;/Keyword&gt;
        ///&lt;Keyword&gt;FILLFACTOR&lt;/Keyword&gt;
        ///&lt;Keyword&gt;RAI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLKeywords {
            get {
                return ResourceManager.GetString("SQLKeywords", resourceCulture);
            }
        }
    }
}
