using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using Generator.Properties;

namespace Generator.CodeGenerators.TableModuleWSL
{
    public class UcTMwServiceLayerGenerator : UserControl
    {
        private IContainer components;
        private TabPage tabPageSPs;
        private TextBox txtSPs;
        private TabPage tabPageEntity;
        private TextBox txtEntities;
        private Label label7;
        private Label label4;
        private Label label5;
        private Label label3;
        private Label label2;
        private Label label1;
        private TextBox txtInfrastructure;
        private TextBox txtBusinessLayerSupertype;
        private FolderBrowserDialog folderBrowserDialog1;
        private Label lblNamespaceInfo;
        private TabPage tabPageData;
        private TextBox txtDataLayer;
        private TabPage tabPageDSupertype;
        private TextBox txtDataSupertype;
        private TabPage tabPageBSupertype;
        private TabPage tabPageInfrastructure;
        private Label label6;
        private TextBox txtNamespace;
        private TextBox txtDomainLogic;
        private Button btnSave;
        private TreeView tvwTables;
        private Button btnGenerate;
        private TabPage tabPageBusiness;
        private Label lblGenerationInfo;
        private TabControl tabControlOutput;
        private TabPage tabPageBlockDiagram;
        private SplitContainer splcntQueryAndResults;
        private Button btnFillTables;
        private Button btnOptions;
        private ImageList imgListTablesTreeView;
        private Label label12;
        private Label label13;
        private PictureBox pictureBox1;

        public UcTMwServiceLayerGenerator()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = (IContainer)new Container();
            ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(UcTMwServiceLayerGenerator));
            this.tabPageSPs = new TabPage();
            this.txtSPs = new TextBox();
            this.tabPageEntity = new TabPage();
            this.txtEntities = new TextBox();
            this.label7 = new Label();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label3 = new Label();
            this.label2 = new Label();
            this.label1 = new Label();
            this.txtInfrastructure = new TextBox();
            this.txtBusinessLayerSupertype = new TextBox();
            this.folderBrowserDialog1 = new FolderBrowserDialog();
            this.lblNamespaceInfo = new Label();
            this.tabPageData = new TabPage();
            this.txtDataLayer = new TextBox();
            this.tabPageDSupertype = new TabPage();
            this.txtDataSupertype = new TextBox();
            this.tabPageBSupertype = new TabPage();
            this.tabPageInfrastructure = new TabPage();
            this.label6 = new Label();
            this.txtNamespace = new TextBox();
            this.txtDomainLogic = new TextBox();
            this.btnSave = new Button();
            this.tvwTables = new TreeView();
            this.btnGenerate = new Button();
            this.tabPageBusiness = new TabPage();
            this.lblGenerationInfo = new Label();
            this.tabControlOutput = new TabControl();
            this.tabPageBlockDiagram = new TabPage();
            this.label12 = new Label();
            this.label13 = new Label();
            this.splcntQueryAndResults = new SplitContainer();
            this.btnOptions = new Button();
            this.imgListTablesTreeView = new ImageList(this.components);
            this.btnFillTables = new Button();
            this.pictureBox1 = new PictureBox();
            this.tabPageSPs.SuspendLayout();
            this.tabPageEntity.SuspendLayout();
            this.tabPageData.SuspendLayout();
            this.tabPageDSupertype.SuspendLayout();
            this.tabPageBSupertype.SuspendLayout();
            this.tabPageInfrastructure.SuspendLayout();
            this.tabPageBusiness.SuspendLayout();
            this.tabControlOutput.SuspendLayout();
            this.tabPageBlockDiagram.SuspendLayout();
            this.splcntQueryAndResults.Panel1.SuspendLayout();
            this.splcntQueryAndResults.Panel2.SuspendLayout();
            this.splcntQueryAndResults.SuspendLayout();
            ((ISupportInitialize)this.pictureBox1).BeginInit();
            this.SuspendLayout();
            this.tabPageSPs.Controls.Add((Control)this.txtSPs);
            this.tabPageSPs.Location = new Point(4, 22);
            this.tabPageSPs.Name = "tabPageSPs";
            this.tabPageSPs.Padding = new Padding(3);
            this.tabPageSPs.Size = new Size(516, 436);
            this.tabPageSPs.TabIndex = 0;
            this.tabPageSPs.Text = "Stored Procs";
            this.tabPageSPs.UseVisualStyleBackColor = true;
            this.txtSPs.Dock = DockStyle.Fill;
            this.txtSPs.Location = new Point(3, 3);
            this.txtSPs.Multiline = true;
            this.txtSPs.Name = "txtSPs";
            this.txtSPs.ScrollBars = ScrollBars.Both;
            this.txtSPs.Size = new Size(510, 430);
            this.txtSPs.TabIndex = 0;
            this.tabPageEntity.Controls.Add((Control)this.txtEntities);
            this.tabPageEntity.Location = new Point(4, 22);
            this.tabPageEntity.Name = "tabPageEntity";
            this.tabPageEntity.Size = new Size(516, 436);
            this.tabPageEntity.TabIndex = 3;
            this.tabPageEntity.Text = "Entities";
            this.tabPageEntity.ToolTipText = "Data Transfer Objects";
            this.tabPageEntity.UseVisualStyleBackColor = true;
            this.txtEntities.Dock = DockStyle.Fill;
            this.txtEntities.Location = new Point(0, 0);
            this.txtEntities.Multiline = true;
            this.txtEntities.Name = "txtEntities";
            this.txtEntities.ScrollBars = ScrollBars.Both;
            this.txtEntities.Size = new Size(516, 436);
            this.txtEntities.TabIndex = 2;
            this.label7.Anchor = AnchorStyles.None;
            this.label7.AutoSize = true;
            this.label7.BackColor = SystemColors.Control;
            this.label7.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)162);
            this.label7.Location = new Point(153, 401);
            this.label7.Name = "label7";
            this.label7.Size = new Size(82, 13);
            this.label7.TabIndex = 6;
            this.label7.Text = "Entity Layer :";
            this.label4.Anchor = AnchorStyles.None;
            this.label4.AutoSize = true;
            this.label4.BackColor = SystemColors.Control;
            this.label4.Location = new Point(236, 362);
            this.label4.Name = "label4";
            this.label4.Size = new Size(72, 13);
            this.label4.TabIndex = 5;
            this.label4.Text = "Table Module";
            this.label5.Anchor = AnchorStyles.None;
            this.label5.AutoSize = true;
            this.label5.BackColor = SystemColors.Control;
            this.label5.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)162);
            this.label5.Location = new Point(135, 362);
            this.label5.Name = "label5";
            this.label5.Size = new Size(100, 13);
            this.label5.TabIndex = 4;
            this.label5.Text = "Business Layer :";
            this.label3.Anchor = AnchorStyles.None;
            this.label3.AutoSize = true;
            this.label3.BackColor = SystemColors.Control;
            this.label3.Location = new Point(236, 375);
            this.label3.Name = "label3";
            this.label3.Size = new Size(105, 13);
            this.label3.TabIndex = 3;
            this.label3.Text = "Table Data Gateway";
            this.label2.Anchor = AnchorStyles.None;
            this.label2.AutoSize = true;
            this.label2.BackColor = SystemColors.Control;
            this.label2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)162);
            this.label2.Location = new Point(158, 375);
            this.label2.Name = "label2";
            this.label2.Size = new Size(77, 13);
            this.label2.TabIndex = 2;
            this.label2.Text = "Data Layer :";
            this.label1.Anchor = AnchorStyles.None;
            this.label1.BackColor = SystemColors.Control;
            this.label1.Font = new Font("Tahoma", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte)162);
            this.label1.Location = new Point(142, 13);
            this.label1.Name = "label1";
            this.label1.Size = new Size(229, 29);
            this.label1.TabIndex = 1;
            this.label1.Text = "Table Module w/ Service Layer";
            this.label1.TextAlign = ContentAlignment.MiddleCenter;
            this.txtInfrastructure.Dock = DockStyle.Fill;
            this.txtInfrastructure.Location = new Point(3, 3);
            this.txtInfrastructure.Multiline = true;
            this.txtInfrastructure.Name = "txtInfrastructure";
            this.txtInfrastructure.ScrollBars = ScrollBars.Both;
            this.txtInfrastructure.Size = new Size(510, 430);
            this.txtInfrastructure.TabIndex = 5;
            this.txtBusinessLayerSupertype.Dock = DockStyle.Fill;
            this.txtBusinessLayerSupertype.Location = new Point(0, 0);
            this.txtBusinessLayerSupertype.Multiline = true;
            this.txtBusinessLayerSupertype.Name = "txtBusinessLayerSupertype";
            this.txtBusinessLayerSupertype.ScrollBars = ScrollBars.Both;
            this.txtBusinessLayerSupertype.Size = new Size(516, 436);
            this.txtBusinessLayerSupertype.TabIndex = 4;
            this.lblNamespaceInfo.AutoSize = true;
            this.lblNamespaceInfo.Location = new Point(4, 8);
            this.lblNamespaceInfo.Name = "lblNamespaceInfo";
            this.lblNamespaceInfo.Size = new Size(64, 13);
            this.lblNamespaceInfo.TabIndex = 0;
            this.lblNamespaceInfo.Text = "Namespace";
            this.tabPageData.Controls.Add((Control)this.txtDataLayer);
            this.tabPageData.Location = new Point(4, 22);
            this.tabPageData.Name = "tabPageData";
            this.tabPageData.Padding = new Padding(3);
            this.tabPageData.Size = new Size(516, 436);
            this.tabPageData.TabIndex = 1;
            this.tabPageData.Text = "Data Layer";
            this.tabPageData.ToolTipText = "Table Data Gateway";
            this.tabPageData.UseVisualStyleBackColor = true;
            this.txtDataLayer.Dock = DockStyle.Fill;
            this.txtDataLayer.Location = new Point(3, 3);
            this.txtDataLayer.Multiline = true;
            this.txtDataLayer.Name = "txtDataLayer";
            this.txtDataLayer.ScrollBars = ScrollBars.Both;
            this.txtDataLayer.Size = new Size(510, 430);
            this.txtDataLayer.TabIndex = 1;
            this.tabPageDSupertype.Controls.Add((Control)this.txtDataSupertype);
            this.tabPageDSupertype.Location = new Point(4, 22);
            this.tabPageDSupertype.Name = "tabPageDSupertype";
            this.tabPageDSupertype.Size = new Size(516, 436);
            this.tabPageDSupertype.TabIndex = 5;
            this.tabPageDSupertype.Text = "Data Layer Supertype";
            this.tabPageDSupertype.UseVisualStyleBackColor = true;
            this.txtDataSupertype.Dock = DockStyle.Fill;
            this.txtDataSupertype.Location = new Point(0, 0);
            this.txtDataSupertype.Multiline = true;
            this.txtDataSupertype.Name = "txtDataSupertype";
            this.txtDataSupertype.ScrollBars = ScrollBars.Both;
            this.txtDataSupertype.Size = new Size(516, 436);
            this.txtDataSupertype.TabIndex = 3;
            this.tabPageBSupertype.Controls.Add((Control)this.txtBusinessLayerSupertype);
            this.tabPageBSupertype.Location = new Point(4, 22);
            this.tabPageBSupertype.Name = "tabPageBSupertype";
            this.tabPageBSupertype.Size = new Size(516, 436);
            this.tabPageBSupertype.TabIndex = 6;
            this.tabPageBSupertype.Text = "Business Layer Supertype";
            this.tabPageBSupertype.UseVisualStyleBackColor = true;
            this.tabPageInfrastructure.Controls.Add((Control)this.txtInfrastructure);
            this.tabPageInfrastructure.Location = new Point(4, 22);
            this.tabPageInfrastructure.Name = "tabPageInfrastructure";
            this.tabPageInfrastructure.Padding = new Padding(3);
            this.tabPageInfrastructure.Size = new Size(516, 436);
            this.tabPageInfrastructure.TabIndex = 7;
            this.tabPageInfrastructure.Text = "Infrastructure";
            this.tabPageInfrastructure.UseVisualStyleBackColor = true;
            this.label6.Anchor = AnchorStyles.None;
            this.label6.AutoSize = true;
            this.label6.BackColor = SystemColors.Control;
            this.label6.Location = new Point(236, 401);
            this.label6.Name = "label6";
            this.label6.Size = new Size(162, 13);
            this.label6.TabIndex = 7;
            this.label6.Text = "Entities as Data Transfer Objects";
            this.txtNamespace.Location = new Point(74, 5);
            this.txtNamespace.Name = "txtNamespace";
            this.txtNamespace.Size = new Size(223, 20);
            this.txtNamespace.TabIndex = 4;
            this.txtNamespace.Text = "EmlakMigration";
            this.txtDomainLogic.Dock = DockStyle.Fill;
            this.txtDomainLogic.Location = new Point(0, 0);
            this.txtDomainLogic.Multiline = true;
            this.txtDomainLogic.Name = "txtDomainLogic";
            this.txtDomainLogic.ScrollBars = ScrollBars.Both;
            this.txtDomainLogic.Size = new Size(516, 436);
            this.txtDomainLogic.TabIndex = 2;
            this.btnSave.Location = new Point(368, 3);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new Size(60, 23);
            this.btnSave.TabIndex = 3;
            this.btnSave.Text = "Save";
            this.btnSave.UseVisualStyleBackColor = true;
            this.tvwTables.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.tvwTables.CheckBoxes = true;
            this.tvwTables.Location = new Point(3, 32);
            this.tvwTables.Name = "tvwTables";
            this.tvwTables.Size = new Size(162, 489);
            this.tvwTables.TabIndex = 0;
            this.btnGenerate.Location = new Point(303, 3);
            this.btnGenerate.Name = "btnGenerate";
            this.btnGenerate.Size = new Size(59, 23);
            this.btnGenerate.TabIndex = 2;
            this.btnGenerate.Text = "Generate";
            this.btnGenerate.UseVisualStyleBackColor = true;
            this.tabPageBusiness.Controls.Add((Control)this.txtDomainLogic);
            this.tabPageBusiness.Location = new Point(4, 22);
            this.tabPageBusiness.Name = "tabPageBusiness";
            this.tabPageBusiness.Size = new Size(516, 436);
            this.tabPageBusiness.TabIndex = 2;
            this.tabPageBusiness.Text = "Business Logic Layer";
            this.tabPageBusiness.ToolTipText = "Table Module";
            this.tabPageBusiness.UseVisualStyleBackColor = true;
            this.lblGenerationInfo.Location = new Point(8, 32);
            this.lblGenerationInfo.Name = "lblGenerationInfo";
            this.lblGenerationInfo.Size = new Size(503, 27);
            this.lblGenerationInfo.TabIndex = 5;
            this.tabControlOutput.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.tabControlOutput.Controls.Add((Control)this.tabPageBlockDiagram);
            this.tabControlOutput.Controls.Add((Control)this.tabPageSPs);
            this.tabControlOutput.Controls.Add((Control)this.tabPageEntity);
            this.tabControlOutput.Controls.Add((Control)this.tabPageData);
            this.tabControlOutput.Controls.Add((Control)this.tabPageBusiness);
            this.tabControlOutput.Controls.Add((Control)this.tabPageDSupertype);
            this.tabControlOutput.Controls.Add((Control)this.tabPageBSupertype);
            this.tabControlOutput.Controls.Add((Control)this.tabPageInfrastructure);
            this.tabControlOutput.Location = new Point(3, 63);
            this.tabControlOutput.Name = "tabControlOutput";
            this.tabControlOutput.SelectedIndex = 0;
            this.tabControlOutput.Size = new Size(524, 462);
            this.tabControlOutput.TabIndex = 1;
            this.tabPageBlockDiagram.BackColor = SystemColors.Control;
            this.tabPageBlockDiagram.Controls.Add((Control)this.pictureBox1);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label12);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label13);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label6);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label7);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label4);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label5);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label3);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label2);
            this.tabPageBlockDiagram.Controls.Add((Control)this.label1);
            this.tabPageBlockDiagram.Location = new Point(4, 22);
            this.tabPageBlockDiagram.Name = "tabPageBlockDiagram";
            this.tabPageBlockDiagram.Size = new Size(516, 436);
            this.tabPageBlockDiagram.TabIndex = 4;
            this.tabPageBlockDiagram.Text = "Block Diagram";
            this.label12.Anchor = AnchorStyles.None;
            this.label12.AutoSize = true;
            this.label12.BackColor = SystemColors.Control;
            this.label12.Location = new Point(236, 388);
            this.label12.Name = "label12";
            this.label12.Size = new Size(164, 13);
            this.label12.TabIndex = 13;
            this.label12.Text = "Light (Transaction Manager Only)";
            this.label13.Anchor = AnchorStyles.None;
            this.label13.AutoSize = true;
            this.label13.BackColor = SystemColors.Control;
            this.label13.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)162);
            this.label13.Location = new Point(142, 388);
            this.label13.Name = "label13";
            this.label13.Size = new Size(93, 13);
            this.label13.TabIndex = 12;
            this.label13.Text = "Service Layer :";
            this.splcntQueryAndResults.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.splcntQueryAndResults.Location = new Point(3, 3);
            this.splcntQueryAndResults.Name = "splcntQueryAndResults";
            this.splcntQueryAndResults.Panel1.Controls.Add((Control)this.btnFillTables);
            this.splcntQueryAndResults.Panel1.Controls.Add((Control)this.tvwTables);
            this.splcntQueryAndResults.Panel2.Controls.Add((Control)this.btnOptions);
            this.splcntQueryAndResults.Panel2.Controls.Add((Control)this.lblGenerationInfo);
            this.splcntQueryAndResults.Panel2.Controls.Add((Control)this.txtNamespace);
            this.splcntQueryAndResults.Panel2.Controls.Add((Control)this.btnSave);
            this.splcntQueryAndResults.Panel2.Controls.Add((Control)this.btnGenerate);
            this.splcntQueryAndResults.Panel2.Controls.Add((Control)this.tabControlOutput);
            this.splcntQueryAndResults.Panel2.Controls.Add((Control)this.lblNamespaceInfo);
            this.splcntQueryAndResults.Size = new Size(704, 528);
            this.splcntQueryAndResults.SplitterDistance = 168;
            this.splcntQueryAndResults.TabIndex = 21;
            this.btnOptions.Location = new Point(434, 3);
            this.btnOptions.Name = "btnOptions";
            this.btnOptions.Size = new Size(63, 23);
            this.btnOptions.TabIndex = 6;
            this.btnOptions.Text = "Options...";
            this.btnOptions.UseVisualStyleBackColor = true;
            this.imgListTablesTreeView.ColorDepth = ColorDepth.Depth24Bit;
            this.imgListTablesTreeView.ImageSize = new Size(16, 16);
            this.imgListTablesTreeView.TransparentColor = Color.Transparent;
            this.btnFillTables.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.btnFillTables.Image = (Image)componentResourceManager.GetObject("btnFillTables.Image");
            this.btnFillTables.ImageAlign = ContentAlignment.MiddleLeft;
            this.btnFillTables.Location = new Point(3, 3);
            this.btnFillTables.Name = "btnFillTables";
            this.btnFillTables.Size = new Size(162, 25);
            this.btnFillTables.TabIndex = 6;
            this.btnFillTables.Text = "Fill Tables";
            this.btnFillTables.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnFillTables.UseVisualStyleBackColor = true;
            this.pictureBox1.Anchor = AnchorStyles.None;
           // this.pictureBox1.Image = (Image)Resources.Architectural2;
            this.pictureBox1.Location = new Point(77, 45);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new Size(370, 307);
            this.pictureBox1.TabIndex = 14;
            this.pictureBox1.TabStop = false;
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.Controls.Add((Control)this.splcntQueryAndResults);
            this.Name = "UcTMwServiceLayerGenerator";
            this.Size = new Size(710, 534);
            this.tabPageSPs.ResumeLayout(false);
            this.tabPageSPs.PerformLayout();
            this.tabPageEntity.ResumeLayout(false);
            this.tabPageEntity.PerformLayout();
            this.tabPageData.ResumeLayout(false);
            this.tabPageData.PerformLayout();
            this.tabPageDSupertype.ResumeLayout(false);
            this.tabPageDSupertype.PerformLayout();
            this.tabPageBSupertype.ResumeLayout(false);
            this.tabPageBSupertype.PerformLayout();
            this.tabPageInfrastructure.ResumeLayout(false);
            this.tabPageInfrastructure.PerformLayout();
            this.tabPageBusiness.ResumeLayout(false);
            this.tabPageBusiness.PerformLayout();
            this.tabControlOutput.ResumeLayout(false);
            this.tabPageBlockDiagram.ResumeLayout(false);
            this.tabPageBlockDiagram.PerformLayout();
            this.splcntQueryAndResults.Panel1.ResumeLayout(false);
            this.splcntQueryAndResults.Panel2.ResumeLayout(false);
            this.splcntQueryAndResults.Panel2.PerformLayout();
            this.splcntQueryAndResults.ResumeLayout(false);
            ((ISupportInitialize)this.pictureBox1).EndInit();
            this.ResumeLayout(false);
        }
    }
}
